New Wallet Component
andresmgsl/solana-cohort-june-2022 pull request #106
Opened 2022-08-10 20:46 UTC by WilliamWang2002

Finished new wallet component by modifying solana wallet adapter.

2022-08-10 22:07 UTC, hreyesm requested changes
Ngl, wallet integration looks and works great, but I have so many questions about its implementation. Did you basically reverse-engineered Solana's wallet adapter? There seems to be a lot going on in this PR, so some clarity on the PR description would definitely help.

2022-08-11 00:21 UTC, WilliamWang2002 commented on src/components/common/wallet-adapter/Button.tsx
> +};
I should delete this component since this is not used in our project.

2022-08-11 16:32 UTC, WilliamWang2002 commented on src/components/common/button/index.tsx
> +    onClick?;
Fixed

2022-08-11 16:41 UTC, HaresMahmood approved these changes

2022-08-11 16:42 UTC, hreyesm approved these changes

2022-08-11 16:42 UTC, merged