Fixed Header
andresmgsl/solana-cohort-june-2022 pull request #69
Opened 2022-07-12 18:05 UTC by WilliamWang2002

Change `Header` display from `sticky` to `fixed` to achieve better visual behavior for the `Hero` section

# ScreenShots
## Before
<img width="1261" alt="Screenshot 2022-07-12 105710" src="https://user-images.githubusercontent.com/73449575/178562322-df553b4a-31a6-4f41-a12b-e5ad754d8759.png">
## After
<img width="1268" alt="Screenshot 2022-07-12 105638" src="https://user-images.githubusercontent.com/73449575/178562387-8d36637a-b63d-46aa-9b9b-f5ace0764de5.png">

2022-07-13 17:11 UTC, hreyesm commented
While `fixed` works fine for the current Landing page styling, it doesn't fit the Explorer and Profile pages as the top appears to be cropped:

<img width="1552" alt="Screen Shot 2022-07-13 at 12 06 28" src="https://user-images.githubusercontent.com/36577958/178791000-b0691c10-d9a7-47c9-ae35-37286c054c42.png">

<img width="1552" alt="Screen Shot 2022-07-13 at 12 06 41" src="https://user-images.githubusercontent.com/36577958/178791029-690d2592-90d9-4561-8635-5018b9753e74.png">

Could you please make the necessary changes to the layout so that all pages can use the new Header?

2022-07-13 17:12 UTC, hreyesm requested changes
While `fixed` works fine for the current Landing page styling, it doesn't fit the Explorer and Profile pages as the top appears to be cropped:

<img width="1552" alt="Screen Shot 2022-07-13 at 12 06 28" src="https://user-images.githubusercontent.com/36577958/178791000-b0691c10-d9a7-47c9-ae35-37286c054c42.png">

<img width="1552" alt="Screen Shot 2022-07-13 at 12 06 41" src="https://user-images.githubusercontent.com/36577958/178791029-690d2592-90d9-4561-8635-5018b9753e74.png">

Could you please make the necessary changes to the layout so that all pages can use the new Header?

2022-07-22 17:28 UTC, hreyesm commented
Any updates on this? @WilliamWang2002

2022-07-22 17:32 UTC, hreyesm commented
You may also want to merge it into `dev`, since it's now pointing to the `hero-animation` branch.

2022-07-25 19:43 UTC, WilliamWang2002 commented
Decided to change the hero section position rather than the header position. Will submit a new PR

2022-07-25 19:43 UTC, closed without merging